theme: jekyll-theme-minimal
title: ¡Bienvenido a mi página personal! - Diego Ángel Barajas Pérez
description: Bienevenido a mi portafolio personal, aquí estaré actualizando las distintas actividades, habilidades y aptitudes personales, ¡no olvides añadir a marcadores esta página para mantenerte al tanto!
